version: '3'

services:
  web:
    build: .
    command: ["sh", "-c", "sleep 10 && python manage.py migrate && python manage.py runserver 0.0.0.0:8819"]
    volumes:
      - .:/app
    ports:
      - "8819:8819"
    depends_on:
      - db
    environment:
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=54032
      - DJANGO_DB_NAME=recsys
      - DJANGO_DB_USER=postgres
      - DJANGO_DB_PASSWORD=postgres

  db:
    image: postgres
    ports:
      - "54032:54032"
    environment:
      - POSTGRES_DB=recsys
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
